spring:
  application:
    name: eg-fumigacion-queue-kotlin

  # Configuración de DataSource (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5442/facturacion_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  # Configuración de JPA (Hibernate)
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    show-sql: false

    # Estrategia de inicialización de la base de datos:
    # 'update' es recomendable para desarrollo, ya que mantiene los datos existentes.
    hibernate:
      ddl-auto: update

  # Configuración de RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
  # Configuración de Redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redisquero